#!/usr/bin/env sh

# Unload the macOS WindowManager process
# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp \
	mouse_modifier fn \
	window_animation_duration 0.0 \
	window_opacity off \
	window_opacity_duration 0.0 \
	window_placement second_child \
	window_shadow float \
	window_topmost off \
	window_zoom_persist off \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 8
# yabai external_bar all:35:0
yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config window_border_hidpi on
yabai -m config window_border_radius 12
yabai -m config window_border_blur off
yabai -m config active_window_border_color "0xFF7aa2f7"
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap
# yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse autoraise

# yabai -m space $(yabai -m query --displays | jq -r ".[1].spaces[0]") --
# Set all padding and gaps to 20pt (default: 0)
# yabai -m config top_padding    12
# yabai -m config bottom_padding 12
# yabai -m config left_padding   12
# yabai -m config right_padding  12
# yabai -m config window_gap     12

# Override gaps for space 2 only
# yabai -m config --space 2 window_gap 0

# yabai -m config window_opacity on
# # yabai -m config window_opacity_duration 0
# yabai -m config active_window_opacity 1
# yabai -m config normal_window_opacity 0.9
# # yabai -m config window_border off
# yabai -m config active_window_border_color "0xFF000000"
#

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^ColorSlurp$" manage=off
yabai -m rule --add app="^Python" manage=off

# Vscode Opacity
# yabai -m rule --add app="^Code$" opacity=0.9
